### PR TITLE
Prevent breaking flickity when using slash URLs

### PR DESCRIPTION
**Pull request by tristantbg**
For example:
http://test.com/#/
http://test.com/#123

https://www.w3.org/TR/CSS21/syndata.html#characters

### CODE REVIEW

**Comment by desandro** [comment]
Thank you for reporting this bug and for this PR!

Yours is a good solution, but I prefer to approach it like so:

``` js
proto.queryCell = function( selector ) {
  if ( typeof selector == 'number' ) {
    // use number as index
    return this.cells[ selector ];
  }
  if ( typeof selector == 'string' ) {
    // do not select invalid selectors from hash: #123, #/. #791
    if ( selector.match(/^[#\.]?[\d\/]/) ) {
      return;
    }
    // use string as selector, get element
    selector = this.element.querySelector( selector );
  }
  // get cell from element
  return this.getCell( selector );
};
```

What do you think?

**Comment by tristantbg** [comment]
That's much better! I knew that you will have a more adapted way of doing it :)

**Comment by desandro** [comment]
Okay, this fix is in. It will be a part of the next release. Thanks again for your contribution here! 🌈 🐻

**Comment by desandro** [comment]
This fix has been released with [v2.2.0](https://github.com/metafizzy/flickity/releases/tag/v2.2.0). Thanks again!

**Pull request closed without merging**
