### PR TITLE
Event data when selectedIndex has changed

### PR DESCRIPTION
**Pull request by stevemayhew**
Felicity calls the select() method internally simply to refresh the
current selected cell.  This makes it impossible to tell if the
selection has changed from the event handler.  Simple change, add the
previous index to the handler arguments (possibly undefined of course)

### CODE REVIEW

**Comment by stevemayhew** [comment]
If the documentation is available in github I can update it as well.  This change allows the consumer of the cellSelect event to deal with it intelligently (like if you want to use it to lazy update content or synchronize two Flickity Galleries).

**Comment by desandro** [comment]
Thanks for this contribution. I'm not sure I see the need for this addition. You could keep track of the previous selectedIndex in domain code

``` js
var prevSelectedIndex;
flkty.on( 'cellSelect', function() {
  if ( flkty.selectedIndex = prevSelectedIndex ) {
    console.log('no change');
  } else {
    console.log('changed selected index')
  }
  prevSelectedIndex = flkty.selectedIndex;
}
```

**Comment by stevemayhew** [comment]
It get's messy, there are multiple Flickity's managed in the code.   

Maybe a better solution would be not to signal the cellSelect event when selected index does not change, but I see from the code that select() is being used to refresh the cell for Lazy Load, on activate(), cellChange() and enough other places that it looked like a much more risky change.

**Comment by desandro** [comment]
I see your point. I'll keep this PR open if others are interested.

**Comment by desandro** [comment]
I have decided not to merge this PR. All the same, thank you for this contribution. I encourage you to continue being involved in open source.

**Pull request closed without merging**
