### PR TITLE
Dispatch activate and deactivate events. Namespace all events

### PR DESCRIPTION
**Pull request by evoactivity**
I found myself needing to run other JS upon activation or deactivation of flickity, so I changed emit to dispatchEvent.

In dispatch event I've also namespaced the events to avoid any clashes with other libraries or events on the same page.

This seems to have pulled in an updated version of your utils into the packaged version also.

### CODE REVIEW

**Comment by desandro** [comment]
Thanks for this contribution. It may not be necessary. You can listen to `activate` and `deactivate` without them being trigged as a jQuery event:

``` js
// with jQuery
$gallery.flickity( 'on', 'activate', function() {} );
// vanilla JS
flkty.on( 'activate' function() {} );
```

As for namespacing, this may be useful, but the issue hasn't been brought up yet.

I'll the PR open for a while to let other discover it.

**Comment by evoactivity** [comment]
Ok, maybe that could be added to the docs? I looked at how the events that are in the docs were implemented and they use dispatchEvent so you can do $gallery.on('event', fn); that won't work with activate or deactivate in their current state. 

But... wouldn't a consistent way to listen for all events from flickity be preferable?

I can listen to cellSelect like so
    // jQuery
    $gallery.on( 'cellSelect', function() {
        console.log( 'Flickity select ' + flkty.selectedIndex )
    })
    // vanilla JS
    flkty.on( 'cellSelect', function() {...})

So shouldn't I be able to listen to activate and deactivate in the same way?

**Comment by desandro** [comment]
It's a tradeoff. I do not document `activate` and `deactivate` as these are internal events used within Flickity and Flickity add-ons. Your issue is the first to identify a need for them. If others raise this issue, I'll re-evaluate.

**Comment by desandro** [comment]
Closing this PR. Been quiet for a while. Thanks again for the code! :whale:

**Pull request closed without merging**
