### PR TITLE
Added new option "dynamicGalleryHeight"

### PR DESCRIPTION
**Pull request by komunyako**
This allow slider take height of selected element and assing it to slider viewport.
Animation based on transitions.

Use carefully with multiple visible items, cause it will shrink some higher elements.
Maybe we should check heights of all visible elements, find maximum value and don't allow changing height if selected item smaller than this value.

But for now this option needed to be able set dynamic gallery with full width items.

### CODE REVIEW

**Comment by desandro** [comment]
Hey thanks for taking a shot at this. I'll eventually be implementing a feature like this into Flickity. Some notes, if you want to take another shot at it:

1. It should work by listening to `cellSelect`
2. Cells already have height measured. Check out `cell.js` to see what's going on in there.

**Comment by komunyako** [comment]
Thanks for reply!

1. Clarify me on that: I need attach method to `cellSelect` through `EventEmitter.addListener()` when we `activate` plugin?

    ``` js
if ( this.options.dynamicGalleryHeight ) {
  this.addListener( 'cellSelect', this.dynamicGalleryHeight );
}
```

2. So i should use `getCell` method like this, right?
    ``` js
this.viewport.style.height = this.getCell(this.selectedElement).size.outerHeight + 'px';
```

**Comment by swus13** [comment]
@desandro will this feature added in the master any time soon?

**Comment by desandro** [comment]
Thanks again for this contribution. I implemented a different solution for [Flickity v2's `adaptiveHeight` option](http://flickity.metafizzy.co/options.html#adaptiveheight). I appreciate your effort here and hope you continue to get involved in open source!

**Pull request closed without merging**
