### PR TITLE
Slide by group

### PR DESCRIPTION
**Pull request by stevemayhew**
This combines two of my branches and pull requests into one, and solves an much voted for issue: 
  https://github.com/metafizzy/flickity/issues/22

### CODE REVIEW

**Comment by desandro** [comment]
Thanks so much for this contribution. This is a nice solution to address sliding-by-group.

My goal for slide-by-group is to drag multiple cells as one. This way, it addresses page dots, prev/next buttons, and dragging. This PR is works, but only for prev/next buttons. I'll keep the PR open so others can check it out.

I'd recommend removing the `.iml`, `.ipr`, and `.iws` files as they won't be needed if other devs are interested in using this branch.

**Comment by stevemayhew** [comment]
Thanks,
Yes…  I keep adding these to .gitignore.  They are intellij project files.  
Will do a rm —cached and push that once we finalize on the pull.   BTW, you can close out my other pull for cell-visible, since this includes it

Also, I’m happy to update docs and share the demo.   Exposing a function and interface with a default implementation in the main Flickity code is the best way to satisfy a wide variety of often divergent use cases.

Also, IMHO the drag is a totally different case, the drag distance and velocity should set how big the ‘group’ of cells that are moved is.

For the dots, exposing a function that give the page size (similar to what was done for prev/next) gives people infinite flexibility for move by page as well.

Just my thoughts, all the best.
Steve

**Comment by amdad** [comment]
@desandro
> My goal for slide-by-group is to drag multiple cells as one. This way, it addresses page dots, prev/next buttons, and dragging. 

+1 :+1:  This is how it should be. Great.

**Comment by desandro** [comment]
Thanks again for this contribution. I implemented a different solution for [Flickity v2's `groupCells` option](http://flickity.metafizzy.co/options.html#groupcells). I appreciate your effort here and hope you continue to get involved in open source!

**Pull request closed without merging**
