### PR TITLE
Creates a dragThreshold configurable property

### PR DESCRIPTION
**Pull request by TylerFisher**
Adds a `dragThreshold` configurable property for determining how many pixels to swipe before starting the drag.

### CODE REVIEW

**Comment by desandro** [comment]
Thanks for this contribution. This is a nice little edition. Mind elaborating on why you need this option?

---

**+1 or add :+1: reaction** to the initial comment  if you'd like to see this code merged into Flickity.

**Comment by TylerFisher** [comment]
We've built elections.npr.org based around flickity, and we have a number of cards that can have pretty deep scrolls on mobile depending on the content at that time. We noticed in testing that it was pretty easy with the default threshold to accidentally trigger a select event while scrolling.

**Comment by desandro** [comment]
Thanks for clearing that up. I'd see what kind of public interest is out there for this feature before I merge.

Whoa, this site is awesome! Using Flickity for a full-page content slider, with vertical scrolling content inside? I honestly didn't think it was possible :grin:

**Comment by desandro** [comment]
Looks like there already is enough interest in #138. I'll merge this feature in for the next release.

**Comment by eads** [comment]
@desandro the vertical scrolling content actually works really nicely! There's a weird text-input focus bug on mobile that isn't due to flickity per se but rather would affect any page with content centered inside an absolutely positioned full-screen container.

Also we're setting aside some budget to donate to you for your tools -- we use them a lot and appreciate the quality.

**Comment by desandro** [comment]
This PR has been merged into the `v2` branch. It will be part of the Flickity v2 release. Thank you so much for this code!

**Pull request merged**
