### PR TITLE
[RFR] Added `is-previous` and `is-next` classes

### PR DESCRIPTION
**Pull request by HugoGiraudel**
@smartmike and I noticed that Flickity does not add classes for previous and next items in the gallery. This small pull-request should add those.

@desandro Please, feel free to discard if you feel like this is a feature that should not be part of the core. We needed it in our project and thought it might be helpful for others as well.

### CODE REVIEW

**Comment by desandro** [comment]
Hi Hugo! Thanks so much for this contribution. This is great to see.

Yeah, I feel this kind of code is best left to individual developers to implement, rather than adding to Flickity's core functionality.

Another way to do this is to use Flickity's extendable API. See demo http://codepen.io/desandro/pen/MagWrN

``` js
Flickity.createMethods.push('_createPrevNextCells');

Flickity.prototype._createPrevNextCells = function() {
  this.on( 'cellSelect', this.setPrevNextCells );
};

Flickity.prototype.setPrevNextCells = function() {
  // remove classes
  if ( this.previousCell ) {
    classie.remove( this.previousCell.element, 'is-previous' );
  }
  if ( this.nextCell ) {
    classie.remove( this.nextCell.element, 'is-next' );
  }
  // set cells
  this.previousCell = this.cells[ this.selectedIndex - 1 ];
  this.nextCell = this.cells[ this.selectedIndex + 1 ];
  // add classes
  if ( this.previousCell ) {
    classie.add( this.previousCell.element, 'is-previous' );
  }
  if ( this.nextCell ) {
    classie.add( this.nextCell.element, 'is-next' );
  }
};
```

I've added this demo to the [Extra demos](http://flickity.metafizzy.co/extras.html#extra-demos)

I'll leave this PR open for a while so others can take a look.

**Comment by HugoGiraudel** [comment]
Alright! :)

**Comment by desandro** [comment]
Closing this PR now

**Comment by laurent-d** [comment]
Hi @desandro, thanks your amazing work, but the pen and the method seems not working now, the prototype methods did change ?

**Comment by desandro** [comment]
@laurent-d Fixed! The pen has been updated for Flickity v2

**Comment by laurent-d** [comment]
Thanks a lot @desandro, if you want to see the result of your update : [http://avant-garde.io/ofiv/](http://avant-garde.io/ofiv/)
It's a combination with object fit for a responsive full slider and fade effect. Hope you like it !

**Pull request closed without merging**
