### PR TITLE
Select cell when tabbed to input in different cell

### PR DESCRIPTION
**Pull request by andrewstuart**
This fixes issues found with tab selection causing an offset that
couldn't be easily corrected apart from reloading the slider.

### CODE REVIEW

**Comment by desandro** [comment]
Thank you for this contribution! I'll have to play around with this for a bit to see how it works.

**Comment by andrewstuart** [comment]
Sounds good. The issue I noticed, more specifically, was that if you tab through elements (e.g. contained links) inside the slider, the browser will automatically scroll without changing the offset.  So when I tried to drag or use the buttons to go back to the beginning, flickity already thought it was at zero offset, and snapped back to where it had been (not viewing the highlighted item).

This should make tabbing into cells automatically trigger focus for that cell, if you're looking for a concrete way to see the effect.

In retrospect, it might be a good idea to make this behavior optional (or opt-out), as I'm sure there are cases where ignoring focus could be desirable.

Let me know if you want me to throw an option in and if so, whether you think it should be on/off by default. :-)

**Comment by andrewstuart** [comment]
Hey @desandro, have you had a chance to peek at the functionality/implementation yet? We'd definitely like to be able to switch back to tracking the official branch rather than our fork. :-)

Thanks!

**Comment by desandro** [comment]
Nope, not yet! But I am planning on a major version upgrade starting in the next month. I'd like to review this and other PRs at that time. Thanks for your patience!

**Comment by desandro** [comment]
I've decided not to add this feature for Flickity v2. While I continue to find this feature valuable, I wasn't ready to add it in. I'll keep the issue open for others to view.

**Pull request closed without merging**
