### PR TITLE
Lazy load align

### PR DESCRIPTION
**Pull request by JasonTheAdams**
Codepen Example: http://codepen.io/JasonTheAdams/pen/PqKPEd?editors=101

Presently, the lazyLoadAdjacent always uses the getAdjacentCellElements function, which isn't very useful if the cellAlign is set to left/right. If, for example, you're set to left align and are displaying four at a time, that means you need to have lazyLoadAdjacent set to 8 in order to load the four visible images. That's obviously not terribly efficient as unused images are being loaded.

I wrote two extra helper functions, getNextCellElements and getPrevCellElements that work just like getAdjacentCellElements but only in a single direction (looping if wrapAround is true). The lazy-loader then determines which to use depending on what the cell alignment is.

Hope this helps! :)

### CODE REVIEW

**Comment by JasonTheAdams** [comment]
Oh, and I apologize for the last commit. I dumbly added the pkgd files and pushed in the previous commit. The final diff, at time of making this, are just the flickity.js and lazyload.js files.

**Comment by desandro** [comment]
Thanks for this contribution. I understand the problem it resolves. Rather than adding more logic to resolve it, I prefer to keep it as is. This way, lazyLoadAdjacent works the same way regardless of cellAlign. It's simpler to explain and easier to manage future development.

I'll leave this PR open for a while to see other's interest.

**Comment by JasonTheAdams** [comment]
What would you think about splitting lazyLoadAdjacent into lazyLoadNext and lazyLoadPrev (or in addition to), for more explicit control? The biggest issue I have with lazyLoadAdjacent alone is that it can end up forcing you to load quite a bit more than is necessary, effectively nullifying the benefit of lazy loading.

For example, I have one section that's 5 slides left aligned. In order to get them all to be loaded, I have to set lazyLoadAdjacent to 5, which also loads 4 invisible slides. At times I may only have 10 slides, which means that there's only 1 that's not actually loading initially.

Curious of your thoughts.

**Comment by desandro** [comment]
I think there's one a couple scenarios when lazyloading adjacent cells in both direction is poor:

+ Initializing Flickity with `cellAlign: 'left'` or `right`, displaying multiple cells within the carousel (the scenario you first mentioned), and `wrapAround: true`
+ Selecting a distant cell in a carousel with `cellAlign: 'left'` or `right` and displaying multiple cells. Like going from cell 1 to cell 10, loading adjacent 4 * 2 cells.

In other scenarios, loading adjacent cells in both directions isn't that bad of a thing. When wrapAround is disabled, there's no oversize initial load because there's no adjacent cells in the previous direction. Nor will there an oversize load when selecting next cells because previous cells will already have been loaded.

You're right in that we can probably handle this more carefully and it would be more performant. But I feel it's a micro-optimization. I've recently merged the `lazyLoadAdjacent` option into `lazyLoad` to simplify them even more.

**Comment by desandro** [comment]
Thanks again for this contribution, but I've decided to not implement this code. I hope you continue to be involved in open source! 🌈🐻

**Pull request closed without merging**
